[versions]

kotlin  = "2.4.0"  # https://github.com/JetBrains/kotlin
publish = "0.36.0" # https://github.com/vanniktech/gradle-maven-publish-plugin

[plugins]

multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
