#file: noinspection SpellCheckingInspection
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gradle/actions/wrapper-validation@v4
      - name: build
        run: |
          docker image     build                                          --tag project-image .
          docker container create                --name project-container       project-image ./gradlew build
          docker container start --attach --interactive project-container
